/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Version {
  buildBranch?: string;
  buildDate?: string;
  commitDate?: string;
  commitHash?: string;
  version?: string;
}
