/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Ahb } from '../models/ahb';
import { getAhb$Csv } from '../fn/ahb/get-ahb-csv';
import { GetAhb$Csv$Params } from '../fn/ahb/get-ahb-csv';
import { getAhb$Json } from '../fn/ahb/get-ahb-json';
import { GetAhb$Json$Params } from '../fn/ahb/get-ahb-json';
import { getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet } from '../fn/ahb/get-ahb-vnd-openxmlformats-officedocument-spreadsheetml-sheet';
import { GetAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params } from '../fn/ahb/get-ahb-vnd-openxmlformats-officedocument-spreadsheetml-sheet';
import { getFormatVersions } from '../fn/ahb/get-format-versions';
import { GetFormatVersions$Params } from '../fn/ahb/get-format-versions';
import { getPruefis } from '../fn/ahb/get-pruefis';
import { GetPruefis$Params } from '../fn/ahb/get-pruefis';


/**
 * Everything about AHB documents
 */
@Injectable({ providedIn: 'root' })
export class AhbService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAhb()` */
  static readonly GetAhbPath = '/api/ahb/{format-version}/{pruefi}';

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAhb$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$Json$Response(params: GetAhb$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Ahb>> {
    return getAhb$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAhb$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$Json(params: GetAhb$Json$Params, context?: HttpContext): Observable<Ahb> {
    return this.getAhb$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Ahb>): Ahb => r.body)
    );
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response(params: GetAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet(params: GetAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params, context?: HttpContext): Observable<Blob> {
    return this.getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAhb$Csv()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$Csv$Response(params: GetAhb$Csv$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return getAhb$Csv(this.http, this.rootUrl, params, context);
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAhb$Csv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$Csv(params: GetAhb$Csv$Params, context?: HttpContext): Observable<Blob> {
    return this.getAhb$Csv$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `getFormatVersions()` */
  static readonly GetFormatVersionsPath = '/api/format-versions';

  /**
   * Get a list of all available format versions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFormatVersions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFormatVersions$Response(params?: GetFormatVersions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return getFormatVersions(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of all available format versions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFormatVersions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFormatVersions(params?: GetFormatVersions$Params, context?: HttpContext): Observable<Array<string>> {
    return this.getFormatVersions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `getPruefis()` */
  static readonly GetPruefisPath = '/api/format-versions/{format-version}/pruefis';

  /**
   * Get a list of all available Pruefidentifikators for a given format version.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPruefis()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPruefis$Response(params: GetPruefis$Params, context?: HttpContext): Observable<StrictHttpResponse<(Array<string> | Array<{
'pruefi'?: string;
'description'?: string;
}>)>> {
    return getPruefis(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of all available Pruefidentifikators for a given format version.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPruefis$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPruefis(params: GetPruefis$Params, context?: HttpContext): Observable<(Array<string> | Array<{
'pruefi'?: string;
'description'?: string;
}>)> {
    return this.getPruefis$Response(params, context).pipe(
      map((r: StrictHttpResponse<(Array<string> | Array<{
'pruefi'?: string;
'description'?: string;
}>)>): (Array<string> | Array<{
'pruefi'?: string;
'description'?: string;
}>) => r.body)
    );
  }

}
